site_name: GitFica Docs
repo_url: https://github.com/fga-eps-mds/2025.1-SGI-Docs
repo_name: SGI Docs
repo_type: github
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
theme:
  name: material
  language: pt-BR
  font:
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: "#2B009D"
      accent: "#5F29F4"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#2B009D"
      accent: "#5F29F4"
      custom:
        background: "#1E2432"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/custom.css
